# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Complex UI 2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Complex UI 2

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Stripe', '19.0.1'
pod 'Alamofire', '~> 5.2'
pod 'lottie-ios'
pod 'SimpleCCForm'
pod 'SwiftyJSON', '~> 4.0'

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


end
